version: '3.5'

networks:
  inception:

services:

# #====MARIADB====

  mariadb:
    container_name: mariadb
    image: mariadb
    env_file: .env
    build:
      context: ./requirements/mariadb
      args:
         - DB_NAME=${DB_NAME}
         - DB_USER=${DB_USER}
         - DB_PASSWORD=${DB_PASSWORD}
         - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    networks:
      - inception
    volumes:
      - mariadb_vol:/var/lib/mysql
    restart: unless-stopped
    #if there is any crash we restart the container automatically
    # healthcheck:
    #   test: "echo hello"

  # #====WORDPRESS====

  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: ./requirements/wordpress
    volumes:
      - wordpress_vol:/var/www/wordpress
    env_file: .env
    depends_on:
      - mariadb
        # condition: service_healthy
    networks:
      - inception
    restart: unless-stopped

#=====NGINX======

  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - wordpress_vol:/var/www/wordpress
    depends_on:
      - wordpress
    build: ./requirements/nginx
    networks:
      - inception
    ports:
      - 443:443
    restart: unless-stopped

#===============BONUS PART====================

#====== FTP SERVER =========

  ftp-server:
    container_name: ftp-server
    image: ftp
    build: ./requirements/bonus/ftp
    ports:
      - "28:28"
      - "21100-21110:21100-21110"
    volumes:
      - "wordpress_vol:/var/www/wordpress"
    networks:
      - inception
    restart: always
    environment:
      FTP_USR: ${FTP_USR}
      FTP_PWD: ${FTP_PWD}

#====== REDIS =========

  redis:
    container_name: redis
    image: redis
    depends_on:
      - wordpress
    build:
      context: requirements/bonus/redis
    networks:
      - inception
    volumes:
      - wordpress_vol:/var/www/wordpress
    expose:
      - "6379"
    env_file:
      - .env
    restart: always

#volumes allow to store in a persistent disk the content in a local disk
#Here we are setting up the binding of the volumes with the correct container
volumes:
    mariadb_vol:
      driver: local
      driver_opts:
        device: "/home/mrojas-e/data/mariadb"
        type: none
        o: bind
    wordpress_vol:
      driver: local
      driver_opts:
        type: none
        device: "/home/mrojas-e/data/wordpress"
        o: bind