# version '3.5'

# networks:
#   inception: {}

# services:
#   nginx:
#     image: nginx
#     container_name: nginx
#     build: ./requirements/nginx
#     networks: inception
#     ports: 
#       - 443:443
#     restart: always
version: '3.5'
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    networks:
      - network
    ports:
      - 443:443
    restart: always

networks:
  network:
    driver: bridge

# #====MARIADB====

#   mysql:
#   image: mariadb
#   volumes:
#     - mariadb_vol:/var/lib/mysql
    # env_file:
    #   - .env
#   environment:
#     MYSQL_ROOT_PASSWORD: mysql_root_pass
#     MYSQL_DATABASE: db_name
#     MYSQL_USER: user_name
#     MYSQL_PASSWORD: user_pass
#   restart: always